name: Build Tree-sitter Bundle

on:
  workflow_run:
    workflows: ["Build CLI"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.26.3
   CLI_EXE: csharp-tree-sitter

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            tar_os: windows
            tar_ext: zip
            target: x86_64-windows-msvc
            ext: dll
          - os: windows-2022
            tar_os: windows
            tar_ext: zip
            target: aarch64-windows-msvc
            ext: dll
          - os: ubuntu-24.04
            tar_os: linux
            tar_ext: tar
            target: x86_64-linux-gnu
            ext: so
          - os: ubuntu-24.04
            tar_os: linux
            tar_ext: tar
            target: aarch64-linux-gnu
            ext: so
          - os: macos-15
            tar_os: macos
            tar_ext: tar
            target: x86_64-macos-none
            ext: dylib
          - os: macos-15
            tar_os: macos
            tar_ext: tar
            target: aarch64-macos-none
            ext: dylib

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Init submodules
        run: git submodule update --checkout

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli@${{ env.VERSION }}

      - name: Download ${{ env.CLI_EXE }} CLI
        run: |
          curl -fsSL https://github.com/jcs090218/csharp-tree-sitter/releases/download/${{ env.VERSION }}/cli-${{ matrix.tar_os }}.${{ matrix.tar_ext }} -o cli-${{ matrix.tar_os }}.${{ matrix.tar_ext }}

      - name: Setup ${{ env.CLI_EXE }} CLI (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          tar -xvf cli-${{ matrix.tar_os }}.${{ matrix.tar_ext }} -C "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          chmod -R 777 "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          echo "$RUNNER_TEMP/${{ env.CLI_EXE }}" >> $GITHUB_PATH

      - name: Setup csharp-tree-sitter CLI (Windows)
        if: runner.os == 'Windows'
        run: |
          $dest = Join-Path $env:RUNNER_TEMP "${{ env.CLI_EXE }}"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null
          Expand-Archive -Path "cli-${{ matrix.tar_os }}.${{ matrix.tar_ext }}" -DestinationPath $dest -Force
          "$env:RUNNER_TEMP\${{ env.CLI_EXE }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: csharp-tree-sitter --version

      - run: |
          csharp-tree-sitter build-bundle -i ./repos -o ./bin
