name: Build Tree-sitter

on:
  push:
    branches:
      - main
    paths:
      - TreeSitter/**
      - '**.yml'
      - '**.json'
      # ignore
      - '!**/docs.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/docs.yml'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.1.0

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: jcs-actions/delete-tag-and-release@master
      if: github.ref == 'refs/heads/master'
      continue-on-error: true
      with:
        delete_release: true
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  ci:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            bundle_os: windows
            target: x86_64-windows-msvc
            prefix: ""
            ext: dll
          - os: windows-2022
            bundle_os: windows
            target: aarch64-windows-msvc
            prefix: ""
            ext: dll
          - os: ubuntu-24.04
            bundle_os: ubuntu
            target: x86_64-linux-gnu
            prefix: lib
            ext: so
          - os: ubuntu-24.04
            bundle_os: ubuntu
            target: aarch64-linux-gnu
            prefix: lib
            ext: so
          - os: macos-15
            bundle_os: macos
            target: x86_64-macos-none
            prefix: lib
            ext: dylib
          - os: macos-15
            bundle_os: macos
            target: aarch64-macos-none
            prefix: lib
            ext: dylib

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      # Cross build
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.0

      - name: Build tree-sitter
        working-directory: modules/tree-sitter
        run: zig build -Dbuild-shared=true -Dtarget=${{ matrix.target }} -p ../../output

      - run: ls -a output/
        continue-on-error: true

      - name: Upload binary
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}.${{ matrix.bundle_os }}
          path: output/bin/${{ matrix.prefix }}tree-sitter.${{ matrix.ext }}
          if-no-files-found: error

      - name: Upload for prerelease
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: true
          draft: false
        files: eask_${{ env.VERSION }}_${{ matrix.target }}.${{ env._EXT }}
  