name: Build Tree-sitter

on:
  push:
    branches:
      - main
    paths:
      - TreeSitter/**
      - '**.yml'
      - '**.json'
      # ignore
      - '!**/docs.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/docs.yml'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.26.3
   VS_OUT: Release  # `Release` or `Debug`
   TS_PATH: core/tree-sitter

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: jcs-actions/delete-tag-and-release@master
      if: github.ref == 'refs/heads/master'
      continue-on-error: true
      with:
        delete_release: true
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  ci:
    needs: [prepare]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            bundle_os: windows
            target: x86_64-windows-msvc
            ext: dll
          - os: windows-2022
            bundle_os: windows
            target: aarch64-windows-msvc
            ext: dll
          - os: ubuntu-24.04
            bundle_os: ubuntu
            target: x86_64-linux-gnu
            ext: so
          - os: ubuntu-24.04
            bundle_os: ubuntu
            target: aarch64-linux-gnu
            ext: so
          - os: macos-15
            bundle_os: macos
            target: x86_64-macos-none
            ext: dylib
          - os: macos-15
            bundle_os: macos
            target: aarch64-macos-none
            ext: dylib

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      # Cross build
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.0

      - name: Build tree-sitter (Unix)
        if: runner.os != 'Windows'
        working-directory: ${{ env.TS_PATH }}
        run: zig build -Dbuild-shared=true -Dtarget=${{ matrix.target }} -p ../../output

      - name: Workaround for CMake exporting symbols (Windows)
        if: runner.os == 'Windows'
        run: python ./scripts/fix_windows_cmake_exports.py

      - name: Build tree-sitter (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{ env.TS_PATH }}
        run: |
          cmake -S . -B build/windows/
          msbuild build/windows/tree-sitter.sln -t:rebuild -verbosity:diag -property:Configuration=${{ env.VS_OUT }}

      - name: Upload binary (Unix)
        uses: actions/upload-artifact@v6
        if: runner.os != 'Windows'
        with:
          name: ${{ matrix.target }}.${{ matrix.bundle_os }}
          path: ./output/lib/libtree-sitter.${{ matrix.ext }}
          if-no-files-found: error

      - name: Upload binary (Windows)
        uses: actions/upload-artifact@v6
        if: runner.os == 'Windows'
        with:
          name: ${{ matrix.target }}.${{ matrix.bundle_os }}
          path: ./${{ env.TS_PATH }}/build/windows/${{ env.VS_OUT }}/tree-sitter.${{ matrix.ext }}
          if-no-files-found: error

      - name: Archive dynamic link (Unix)
        if: runner.os != 'Windows'
        run: |
          tar -cf tree-sitter.${{ matrix.target }}.tar ./output/lib/libtree-sitter.${{ matrix.ext }}

      - name: Archive dynamic link (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path ./${{ env.TS_PATH }}/build/windows/${{ env.VS_OUT }}/tree-sitter.${{ matrix.ext }} -DestinationPath tree-sitter.${{ matrix.target }}.zip

      - name: Upload for prerelease (Unix)
        if: github.ref == 'refs/heads/main' && runner.os != 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./tree-sitter.${{ matrix.target }}.tar

      - name: Upload for prerelease (Windows)
        if: github.ref == 'refs/heads/main' && runner.os == 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./tree-sitter.${{ matrix.target }}.zip
  