name: Build CLI

on:
  workflow_run:
    workflows: ["Build Tree-sitter"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.26.3
   VS_OUT: Debug  # `Release` or `Debug`
   DOT_NET: net9.0

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            target: win-x64
          - os: windows-2022
            target: win-arm64
          - os: ubuntu-24.04
            target: linux-x64
          - os: ubuntu-24.04-arm64
            target: linux-arm64
          - os: macos-15-intel
            target: osx-x64
          - os: macos-15
            target: osx-arm64

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build the project
        run: dotnet publish --configuration ${{ env.VS_OUT }} --runtime ${{ matrix.target }} --self-contained true

      - name: Archive executable (Unix)
        if: runner.os != 'Windows'
        run: |
          tar -cf cli.${{ matrix.target }}.tar -C ./TreeSitter.CLI/bin/${{ env.VS_OUT }}/${{ env.DOT_NET }}/${{ matrix.target }}/publish/ .

      - name: Archive executable (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path ./TreeSitter.CLI/bin/${{ env.VS_OUT }}/${{ env.DOT_NET }}/${{ matrix.target }}/publish/*.* -DestinationPath cli.${{ matrix.target }}.zip

      - name: Upload for release (Unix)
        if: github.ref == 'refs/heads/main' && runner.os != 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./cli.${{ matrix.target }}.tar

      - name: Upload for release (Windows)
        if: github.ref == 'refs/heads/main' && runner.os == 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./cli.${{ matrix.target }}.zip
  