name: Build Tree-sitter Bundle

on:
  workflow_run:
    workflows: ["Build CLI"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.26.3
   CLI_EXE: csharp-tree-sitter

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            cli_target: win-x64
            tar_ext: zip
            target: x86_64-windows-msvc
            ext: dll
          - os: windows-2022
            cli_target: win-x64
            tar_ext: zip
            target: aarch64-windows-msvc
            ext: dll
          - os: ubuntu-24.04
            cli_target: linux-x64
            tar_ext: tar
            target: x86_64-linux-gnu
            ext: so
          - os: ubuntu-24.04
            cli_target: linux-x64
            tar_ext: tar
            target: aarch64-linux-gnu
            ext: so
          - os: macos-15-intel
            cli_target: osx-x64
            tar_ext: tar
            target: x86_64-macos-none
            ext: dylib
          - os: macos-15
            cli_target: osx-arm64
            tar_ext: tar
            target: aarch64-macos-none
            ext: dylib

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Init submodules
        run: git submodule update --checkout

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli@${{ env.VERSION }}

      - name: Download ${{ env.CLI_EXE }} CLI
        run: |
          curl -fsSL https://github.com/jcs090218/csharp-tree-sitter/releases/download/${{ env.VERSION }}/cli.${{ matrix.cli_target }}.${{ matrix.tar_ext }} -o cli.${{ matrix.cli_target }}.${{ matrix.tar_ext }}

      - name: Setup ${{ env.CLI_EXE }} CLI (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          tar -xvf cli.${{ matrix.cli_target }}.${{ matrix.tar_ext }} -C "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          chmod -R 777 "$RUNNER_TEMP/${{ env.CLI_EXE }}"
          echo "$RUNNER_TEMP/${{ env.CLI_EXE }}" >> $GITHUB_PATH

      - name: Setup csharp-tree-sitter CLI (Windows)
        if: runner.os == 'Windows'
        run: |
          $dest = Join-Path $env:RUNNER_TEMP "${{ env.CLI_EXE }}"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null
          Expand-Archive -Path "cli.${{ matrix.cli_target }}.${{ matrix.tar_ext }}" -DestinationPath $dest -Force
          "$env:RUNNER_TEMP\${{ env.CLI_EXE }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: csharp-tree-sitter --version

      - name: Compile language grammars
        run: |
          csharp-tree-sitter build-bundle -i ./repos -o ./bin

      - name: Archive grammars (Unix)
        if: runner.os != 'Windows'
        run: |
          tar -cf tree-sitter.${{ matrix.target }}.tar -C ./output/lib libtree-sitter.${{ matrix.ext }}

      - name: Archive grammars (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path ./bin/${{ env.VS_OUT }}/tree-sitter.${{ matrix.ext }}/*.* -DestinationPath .${{ matrix.target }}.zip

      - name: Upload for release (Unix)
        if: github.ref == 'refs/heads/main' && runner.os != 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./bin/*.${{ matrix.ext }}

      - name: Upload for release (Windows)
        if: github.ref == 'refs/heads/main' && runner.os == 'Windows'
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PAT }}
          prerelease: false
          draft: false
          files: ./bin/*.${{ matrix.ext }}
  