name: Build nupkg

on:
  workflow_run:
    workflows: ["Build Tree-sitter Bundle"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   VERSION: 0.26.3
   VS_OUT: Debug  # `Release` or `Debug`
   DOT_NET: net9.0

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Export as nupkg
        run: dotnet pack -c ${{ env.VS_OUT }}

      - name: Upload for release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ env.VERSION }}
          allowUpdates: true
          prerelease: false
          draft: false
          artifacts: |
            ./TreeSitter/bin/${{ env.VS_OUT }}/TreeSitter.*.nupkg
            ./TreeSitter.Bundle/bin/${{ env.VS_OUT }}/TreeSitter.Bundle.*.nupkg
  